### ISSUE TITLE
ブラウザで正しく画面が表示されない

### ISSUE THREAD

**Issue by h-takeyeah** [arumakan1727/taskrader#34]
### 不具合の概要

自分の手元では`./taskrader gui`として起動したブラウザで次のような画面になりました。

![image](https://user-images.githubusercontent.com/61489178/154825586-e137fb5a-13db-49ae-a64c-93ca55ff22c9.png)

### 不具合の再現手順

1. https://github.com/arumakan1727/taskrader/commit/0c9115c5cb11bb89f50e7a5fd5a156339a66b9a1 を`make`する
2. `cd bin && ./taskrader login` して認証情報を入力(今回は学情だけセットしました)する
3. `./taskrader gui`してブラウザを確認する

### 本来望まれる動作

README.mdのスクリーンショットにあるようなデザインの画面が表示されること。

#### 補足

開発者ツールを見たところ，次のようなエラーが出ていました。

```
Uncaught TypeError: r.default is not a constructor
    <anonymous> https://unpkg.com/vue-material:6
    t https://unpkg.com/vue-material:6
    <anonymous> https://unpkg.com/vue-material:6
    t https://unpkg.com/vue-material:6
    <anonymous> https://unpkg.com/vue-material:6
    t https://unpkg.com/vue-material:6
    <anonymous> https://unpkg.com/vue-material:6
    <anonymous> https://unpkg.com/vue-material:6
    <anonymous> https://unpkg.com/vue-material:6
    <anonymous> https://unpkg.com/vue-material:6

Uncaught TypeError: Vue.component is not a function
    <anonymous> http://localhost:8777/file/main.js:1
```

**Vueのバージョンを2.x系に下げるとこれらのエラーが消えました。** 変更箇所と結果のスクリーンショットは次の通りです。

https://github.com/arumakan1727/taskrader/blob/0c9115c5cb11bb89f50e7a5fd5a156339a66b9a1/assets/index.html#L384

```diff
- <script defer src="https://unpkg.com/vue"></script>
+ <script defer src="https://unpkg.com/vue@2"></script> 
```

![image](https://user-images.githubusercontent.com/61489178/154825781-81c4502d-43c9-4f8d-aaee-bb8908749b22.png)

変更前(バージョン指定なし)は`vue@3.2.31`が、変更後(バージョンを2に指定)は`vue@2.6.14`がそれぞれダウンロードされました。(2022/2/20時点)

余談ですが，Vue3.xがリリースされたのはかなり前であり、上記のindex.htmlを見たところ使用するVueのバージョンは指定していないようですので開発者さんの手元でもおそらくブラウザにダウンロードされる`vue.js`ファイルはVue3.xのものだと思います。にもかかわらず今回のエラーが出たのでもしかすると原因は他にあるのかもしれませんが、とりあえずバージョンを下げたら直りましたということで報告します。

### 詳細情報
**Go のバージョン:**
```
go version go1.17.7 linux/amd64
```

**Comment by arumakan1727** [comment]
バグ報告およびエラー解決の試行ありがとうございます。
いま私の方でも同じ不具合が確認でき、vue@v2 を指定したらエラーが消えました。

## 考えられるバグの原因
本アプリで使用している Vue Material は [Vue 3 に対応していないよう](https://github.com/vuematerial/vue-material/issues/2277) なので、この不具合の原因は Vue2 - Vue3 のバージョンの食い違いによるものだと考えられます。  

(おっしゃるとおり Vue3 がリリースされたのはかなり前なのに、我々の開発時点ではエラーなく動作していたのが謎ですが...)

## 対応
CDN で依存ライブラリを読み込んでいる部分の URL にバージョン指定を追加します。
(Vue のみならず axios や Vue Material 等すべて)

**Comment by arumakan1727** [comment]
別件のバグで、ヨウタクさんの先ほどのスクショに「学情の課題取得でエラー: response status was 302 (expect 200)」とありますが、こちらは [既知かつ未知のバグ](https://github.com/szpp-dev-team/gakujo-api/issues/17) なのでご了承ください :bow:
